sum(model.record.solution(end).solution.heatingnetwork.aux_h_pipe_s_in_alpha_1_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.aux_h_pipe_s_in_alpha_2_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.aux_h_pipe_s_in_beta_1_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.aux_h_pipe_s_in_beta_2_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.aux_h_pipe_r_in_alpha_1_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.aux_h_pipe_r_in_alpha_2_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.aux_h_pipe_r_in_beta_1_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.aux_h_pipe_r_in_beta_2_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.h_pipe_s_in_1_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.h_pipe_s_in_2_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.h_pipe_s_out_1_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.h_pipe_s_out_2_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.h_pipe_r_in_1_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.h_pipe_r_in_2_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.h_pipe_r_out_1_residual(:))
sum(model.record.solution(end).solution.heatingnetwork.h_pipe_r_out_2_residual(:))

max(model.record(end).relaxation_error(end).h_pipe_s_in(:))
max(model.record(end).relaxation_error(end).h_pipe_s_out(:))
max(model.record(end).relaxation_error(end).h_pipe_r_in(:))
max(model.record(end).relaxation_error(end).h_pipe_r_out(:))



max(model.record(end).relaxation_error(end).aux_h_pipe_s_in_alpha(:))
max(model.record(end).relaxation_error(end).aux_h_pipe_r_in_alpha(:))
max(model.record(end).relaxation_error(end).aux_h_pipe_s_in_beta(:))
max(model.record(end).relaxation_error(end).aux_h_pipe_r_in_beta(:))