function model_grid(varargin)
if find(strcmp(varargin, 'DisplayTime'))
    DisplayTime = varargin{find(strcmp(varargin, 'DisplayTime'))+1};
else
    DisplayTime = 1;
end
if DisplayTime
    fprintf('%-40s\t\t','- Model grid');
    t0 = clock;
end
%%
global data model;
[loc_gridprice_buy, loc_gridprice_sell] = deal(1,2);                 % grid price
[loc_bus, loc_bustype, loc_volmax, loc_volmin] = deal(1,2,12,13);    % bus
[loc_fbus, loc_tbus, loc_r, loc_x] = deal(2,3,4,5);                  % branch
[loc_devicebus, loc_devicetype, loc_pmax, loc_pmin, ...
    loc_es_cap, loc_es_pchr, loc_es_pdis, ...
    loc_es_etachr, loc_es_etadis, loc_es_loss, ...
    loc_es_capmax, loc_es_capmin, loc_es_capinitial, ...
    loc_gt_eta, loc_gt_loss, loc_gt_etahr, loc_eb_eta] = ...
    deal(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,14);   % device
[loc_tst_cap, loc_tst_hchr, loc_tst_hdis, loc_tst_etachr, loc_tst_etadis, ...
    loc_tst_loss, loc_tst_capmax, loc_tst_capmin, loc_tst_capinitial] = ...
    deal(loc_es_cap, loc_es_pchr, loc_es_pdis, ...
    loc_es_etachr, loc_es_etadis, loc_es_loss, ...
    loc_es_capmax, loc_es_capmin, loc_es_capinitial);
[loc_profilesbus, loc_profilestype] = deal(1,2);       % profiles
[loc_c2, loc_c1, loc_c0, loc_penalty, loc_om] = deal(5,6,7,8,9); % cost

%%
num_period = data.period;
num_bus = size(data.grid.bus,1);
num_branch = size(data.grid.branch,1);
baseKV = data.grid.bus(1,10);        % kV;
set_res = find(data.device.param(:,loc_devicetype) == 1);
set_es = find(data.device.param(:,loc_devicetype) == 2);
set_gt = find(data.device.param(:,loc_devicetype) == 3);
set_eb = find(data.device.param(:,loc_devicetype) == 4);
set_tst = find(data.device.param(:,loc_devicetype) == 5);
set_p_load = find(data.profiles.bus(:,loc_profilestype) == 1);
set_q_load = find(data.profiles.bus(:,loc_profilestype) == 2);
set_res_power = find(data.profiles.bus(:,loc_profilestype) == 3);
% %
busset_res = data.device.param(set_res,loc_devicebus);
busset_es = data.device.param(set_es,loc_devicebus);
busset_gt = data.device.param(set_gt,loc_devicebus);
busset_eb = data.device.param(set_eb,loc_devicebus);
busset_tst = data.device.param(set_tst,loc_devicebus);
busset_p_load = data.profiles.bus(set_p_load,loc_profilesbus);
busset_q_load = data.profiles.bus(set_q_load,loc_profilesbus);
busset_res_power = data.profiles.bus(set_res_power,loc_profilesbus);
complete_busset = [1:num_bus];
%% Define variables
define_vars();
%% Distflow
model_distflow();
%% Bus-Device balance
model_equBusDevice();
%% PCC
model_pcc();
%% Device
model_device();
%% SOC constraints of binary variables
SOC_binary();


%% res & load
% % res
model.cons = model.cons + ( ...
    (model.var.grid.res.p_fore(:,:) == ...
    data.profiles.data(set_res_power, :)') : ...
    '');
% % p load
if ~isempty(setdiff(complete_busset, busset_p_load))
    model.cons = model.cons + ( ...
        (model.var.grid.bus.p_load(:,setdiff(complete_busset, busset_p_load)) ==  ...
        0) : 'p load of bus');
end
if ~isempty(set_p_load)
    model.cons = model.cons + ( ...
        (model.var.grid.bus.p_load(:,busset_p_load) == ...
        data.profiles.data(set_p_load,:)') : 'p load of bus');
end
% % q load
if ~isempty(setdiff(complete_busset, busset_q_load))
    model.cons = model.cons + ( ...
        (model.var.grid.bus.q_load(:,setdiff(complete_busset, busset_q_load)) ==  ...
        0) : 'q load of bus');
end
if ~isempty(set_q_load)  
    model.cons = model.cons + ( ...
        (model.var.grid.bus.q_load(:,busset_q_load) == ...
        data.profiles.data(set_q_load,:)') : 'q load of bus');
end

%% Cost
model_cost();

%%
if DisplayTime
    t1 = clock;
    fprintf('%10.2f%s\n', etime(t1,t0), 's');
end

%% ************************ Sub Functions **************************
%% ---------------------- Define Variables -------------------------
    function define_vars()
        % % pcc
        model.var.grid.pcc.p_state = sdpvar(num_period, 2, 'full');
        model.var.grid.pcc.q_state = sdpvar(num_period, 2, 'full');
        model.var.grid.pcc.p = sdpvar(num_period, 2, 'full');
        model.var.grid.pcc.q = sdpvar(num_period, 2, 'full');
        % % branch
        model.var.grid.branch.p = sdpvar(num_period, num_branch, 'full');
        model.var.grid.branch.q = sdpvar(num_period, num_branch, 'full');
        % % bus
        model.var.grid.bus.vol_bus = sdpvar(num_period, num_bus,'full');
        model.var.grid.bus.p_bus = sdpvar(num_period, num_bus, 'full');
        model.var.grid.bus.q_bus = sdpvar(num_period, num_bus, 'full');
        model.var.grid.bus.p_res = sdpvar(num_period, num_bus, 'full');
        model.var.grid.bus.p_es = sdpvar(num_period, num_bus, 'full');
        model.var.grid.bus.p_gt = sdpvar(num_period, num_bus, 'full');
        model.var.grid.bus.p_eb = sdpvar(num_period, num_bus, 'full');
        model.var.grid.bus.p_load = sdpvar(num_period, num_bus, 'full');
        model.var.grid.bus.q_load = sdpvar(num_period, num_bus, 'full');
        % % device
        % % res
        if ~isempty(set_res)
            model.var.grid.res.p = sdpvar(num_period, length(set_res), 'full');
            model.var.grid.res.p_fore = sdpvar(num_period, length(set_res), 'full');
        end
        % % % es
        if ~isempty(set_es)
            model.var.grid.es.p_chr_state = sdpvar(num_period, length(set_es), 'full');
            model.var.grid.es.p_dis_state = sdpvar(num_period, length(set_es), 'full');
            model.var.grid.es.p_chr = sdpvar(num_period, length(set_es), 'full');
            model.var.grid.es.p_dis = sdpvar(num_period, length(set_es), 'full');
            model.var.grid.es.soc = sdpvar(num_period, length(set_es), 'full');
        end
        % %  gt
        if ~isempty(set_gt)
            model.var.grid.gt.state = sdpvar(num_period, length(set_gt), 'full');
            model.var.grid.gt.gas = sdpvar(num_period, length(set_gt), 'full');
            model.var.grid.gt.p = sdpvar(num_period, length(set_gt), 'full');
            model.var.grid.gt.h = sdpvar(num_period, length(set_gt), 'full');
        end
        % % eb
        if ~isempty(set_eb)
            model.var.grid.eb.p = sdpvar(num_period, length(set_eb), 'full');
            model.var.grid.eb.h = sdpvar(num_period, length(set_eb), 'full');
        end
        % % tst
        if ~isempty(set_tst)
            model.var.grid.tst.h_chr_state = sdpvar(num_period, length(set_tst), 'full');
            model.var.grid.tst.h_dis_state = sdpvar(num_period, length(set_tst), 'full');
            model.var.grid.tst.h_chr = sdpvar(num_period, length(set_tst), 'full');
            model.var.grid.tst.h_dis = sdpvar(num_period, length(set_tst), 'full');
            model.var.grid.tst.soc = sdpvar(num_period, length(set_tst), 'full');
        end
        % % cost
        model.cost.grid.sum = sdpvar(1,1, 'full');
        model.cost.grid.pcc.buy = sdpvar(num_period, 1, 'full');
        model.cost.grid.pcc.sell = sdpvar(num_period, 1, 'full');
        model.cost.grid.res = sdpvar(num_period, 1, 'full');
        model.cost.grid.es = sdpvar(num_period, 1, 'full');
        model.cost.grid.tst = sdpvar(num_period, 1, 'full');
        model.cost.grid.gt = sdpvar(num_period, 1, 'full');
        model.cost.grid.eb = sdpvar(num_period, 1, 'full');
    end

%% ------------------------ Dist Flow ------------------------------
    function model_distflow()
        for i = 1:num_bus
            Upline = find(data.grid.branch(:,loc_tbus) == i);
            Downline = find(data.grid.branch(:,loc_fbus) == i);
            % % bus power
            % % PCC bus
            if isempty(Upline) && ~isempty(Downline)
                model.cons = model.cons + ( ...
                    (model.var.grid.bus.p_bus(:,i) == ...
                    model.var.grid.pcc.p(:,1) - ...
                    model.var.grid.pcc.p(:,2) + ...
                    model.var.grid.bus.p_res(:,i) + ...
                    model.var.grid.bus.p_es(:,i) + ...
                    model.var.grid.bus.p_gt(:,i) - ...
                    model.var.grid.bus.p_eb(:,i) - ...
                    model.var.grid.bus.p_load(:,i)) : ...
                    'p of bus PCC'); %#ok<*BDSCA>
                model.cons = model.cons + ( ...
                    (model.var.grid.bus.q_bus(:,i) == ...
                    model.var.grid.pcc.q(:,1) - ...
                    model.var.grid.pcc.q(:,2) - ...
                    model.var.grid.bus.p_load(:,i)) :  ...
                    'q of bus PCC');
                % % intersaction node & load node
            else
                model.cons = model.cons + ( ...
                    (model.var.grid.bus.p_bus(:,i) == ...
                    model.var.grid.bus.p_res(:,i) + ...
                    model.var.grid.bus.p_es(:,i) + ...
                    model.var.grid.bus.p_gt(:,i) - ...
                    model.var.grid.bus.p_eb(:,i) - ...
                    model.var.grid.bus.p_load(:,i)) : ...
                    'p of bus PCC');
                model.cons = model.cons + ( ...
                    (model.var.grid.bus.q_bus(:,i) == ...
                    -model.var.grid.bus.q_load(:,i)) : ...
                    'q of bus PCC');
            end
            
            % % bus balance
            model.cons = model.cons + ( ...
                (model.var.grid.bus.p_bus(:,i) + ...
                sum(model.var.grid.branch.p(:,Upline), 2) == ...
                sum(model.var.grid.branch.p(:,Downline), 2)) : ...
                'p balance of bus');
            model.cons = model.cons + ( ...
                (model.var.grid.bus.q_bus(:,i) + ...
                sum(model.var.grid.branch.q(:,Upline), 2) == ...
                sum(model.var.grid.branch.q(:,Downline), 2)) : ...
                'q balance of bus');
        end
        
        % % Equation of vol
        for i = 1:num_bus
            Upline = find(data.grid.branch(:,loc_tbus) == i);
            Upbus = data.grid.branch(Upline, loc_fbus);
            if data.grid.bus(i,loc_bustype) == 3  % bus of PCC
                model.cons = model.cons + ( ...
                    (model.var.grid.bus.vol_bus(:,i) == 1) : ...
                    'Vol of PCC');
            else
                model.cons = model.cons + ( ...
                    (model.var.grid.bus.vol_bus(:,i) == ...
                    model.var.grid.bus.vol_bus(:,Upbus) - ...
                    1/baseKV^2*1e-3* ...
                    (data.grid.branch(Upbus, loc_r)* ...
                    model.var.grid.branch.p(:,Upline) + ...
                    data.grid.branch(Upbus, loc_x)* ...
                    model.var.grid.branch.q(:,Upline))) : ...
                    'Vol of bus');
            end
            
            model.cons = model.cons + ( ...
                (data.grid.bus(i,loc_volmin) <= ...
                model.var.grid.bus.vol_bus(:,i) <= ...
                data.grid.bus(i,loc_volmax)) : ...
                'limit of vol_bus');
        end
    end
%% -------------------- Equations of bus & device ------------------
    function model_equBusDevice()
        % % res
        if ~isempty(setdiff(complete_busset,busset_res))
            model.cons = model.cons + ( ...
                (model.var.grid.bus.p_res ...
                (:,setdiff(complete_busset,busset_res)) == 0) : ...
                '');
        end
        % % es
        if ~isempty(setdiff(complete_busset,busset_es))
            model.cons = model.cons + ( ...
                (model.var.grid.bus.p_es ...
                (:,setdiff(complete_busset,busset_es)) == 0) : ...
                '');
        end
        % % gt
        if ~isempty(setdiff(complete_busset,busset_gt))
            model.cons = model.cons + ( ...
                (model.var.grid.bus.p_gt ...
                (:,setdiff(complete_busset,busset_gt)) == 0) : ...
                '');
        end
        % % eb
        if ~isempty(setdiff(complete_busset,busset_eb))
            model.cons = model.cons + ( ...
                (model.var.grid.bus.p_eb ...
                (:,setdiff(complete_busset,busset_eb)) == 0) : ...
                '');
        end
        % % Bus with device
        if ~isempty(set_res)
            model.cons = model.cons + ( ...
                (model.var.grid.bus.p_res(:,busset_res) == ...
                model.var.grid.res.p) : ...
                '');
        end
        if ~isempty(set_es)
            model.cons = model.cons + ( ...
                (model.var.grid.bus.p_es(:,busset_es) == ...
                model.var.grid.es.p_dis - ...
                model.var.grid.es.p_chr) : ...
                '');
        end
        if ~isempty(set_gt)
            model.cons = model.cons + ( ...
                (model.var.grid.bus.p_gt(:,busset_gt) == ...
                model.var.grid.gt.p) : ...
                '');
        end
        if ~isempty(set_eb)
            model.cons = model.cons + ( ...
                (model.var.grid.bus.p_eb(:,busset_eb) == ...
                model.var.grid.eb.p) : ...
                '');
        end
    end

%% -------------------------- PCC ----------------------------------
    function model_pcc()
%         model.cons = model.cons + ( ...
%             (model.var.grid.pcc.p_state(:,1) + ...
%             model.var.grid.pcc.p_state(:,2) == 1) : 'p state of grid');
%         model.cons = model.cons + ( ...
%             (model.var.grid.pcc.q_state(:,1) + ...
%             model.var.grid.pcc.q_state(:,2) == 1) : 'q state of grid');
        model.cons = model.cons + ( ...
            (0 <= model.var.grid.pcc.p_state <=1) : '');
        model.cons = model.cons + ( ...
            (0 <= model.var.grid.pcc.q_state <=1) : '');
        model.cons = model.cons + ( ...
            (0 <= model.var.grid.pcc.p <= ...
            data.grid.p_pcc*model.var.grid.pcc.p_state) : '');
        model.cons = model.cons + ( ...
            (0 <= model.var.grid.pcc.q <= ...
            data.grid.q_pcc*model.var.grid.pcc.q_state) : '');
    end

%% -------------------------- Device -------------------------------
    function model_device()
        %% es
        if ~isempty(set_es)
            model.cons = model.cons + ( ...
                (model.var.grid.es.p_chr_state + ...
                model.var.grid.es.p_dis_state <= 1) : '');
            model.cons = model.cons + ( ...
                (0 <= model.var.grid.es.p_chr <= ...
                model.var.grid.es.p_chr_state .* ...
                (ones(num_period, 1)*data.device.param(set_es, loc_es_pchr)')) : ...
                'limit on p_chr of es');
            model.cons = model.cons + ( ...
                (0 <= model.var.grid.es.p_dis <= ...
                model.var.grid.es.p_dis_state(:,:).* ...
                (ones(num_period, 1)*data.device.param(set_es, loc_es_pdis)')) : ...
                'limit on p_dis of es');
            model.cons = model.cons + ( ...
                (ones(num_period,1) * ...
                data.device.param(set_es, loc_es_capmin)'.* ...
                data.device.param(set_es, loc_es_cap)'<= ...
                model.var.grid.es.soc(:,:) <= ...
                ones(num_period,1) * ...
                data.device.param(set_es, loc_es_capmax)'.* ...
                data.device.param(set_es, loc_es_cap)') : ...
                'limit on cap of es');
            model.cons = model.cons + ( ...
                (model.var.grid.es.soc(end,:) == ...
                data.device.param(set_es, loc_es_capinitial)'.* ...
                data.device.param(set_es, loc_es_cap)') : ...
                'final soc of es');
            t = 1;
            model.cons = model.cons + ( ...
                (model.var.grid.es.soc(t,:) == ...
                (1 - data.device.param(set_es, loc_es_loss)').* ...
                data.device.param(set_es, loc_es_capinitial)'.* ...
                data.device.param(set_es, loc_es_cap)'+ ...
                data.device.param(set_es, loc_es_etachr)'.* ...
                model.var.grid.es.p_chr(t,:) - ...
                1./data.device.param(set_es, loc_es_etadis)'.* ...
                model.var.grid.es.p_dis(t,:)) : ...
                'initial soc of es');
            
            t = 2:num_period;
            model.cons = model.cons + ( ...
                (model.var.grid.es.soc(t,:) == ...
                ones(length(t),1)*(1 - data.device.param(set_es, loc_es_loss)').* ...
                model.var.grid.es.soc(t-1,:) + ...
                ones(length(t),1)*data.device.param(set_es, loc_es_etachr)'.* ...
                model.var.grid.es.p_chr(t,:) - ...
                ones(length(t),1)*1./data.device.param(set_es, loc_es_etadis)'.* ...
                model.var.grid.es.p_dis(t,:)) : ....
                'soc equations of es');
        end
        
        %% tst
        if ~isempty(set_tst)
            model.cons = model.cons + ( ...
                (model.var.grid.tst.h_chr_state + ...
                model.var.grid.tst.h_dis_state <= 1) : '');
            
            model.cons = model.cons + ( ...
                (0 <= model.var.grid.tst.h_chr <= ...
                model.var.grid.tst.h_chr_state .* ...
                (ones(num_period, 1)*data.device.param(set_tst, loc_tst_hchr)')) : ...
                'limit on h_chr of tst');
            model.cons = model.cons + ( ...
                (0 <= model.var.grid.tst.h_dis <= ...
                model.var.grid.tst.h_dis_state(:,:).* ...
                (ones(num_period, 1)*data.device.param(set_tst, loc_tst_hdis)')) : ...
                'limit on h_dis of tst');
            model.cons = model.cons + ( ...
                (ones(num_period,1) * ...
                data.device.param(set_tst, loc_tst_capmin)'.* ...
                data.device.param(set_tst, loc_tst_cap)'<= ...
                model.var.grid.tst.soc(:,:) <= ...
                ones(num_period,1) * ...
                data.device.param(set_tst, loc_tst_capmax)'.* ...
                data.device.param(set_tst, loc_tst_cap)') : ...
                'limit on cap of tst');
            model.cons = model.cons + ( ...
                (model.var.grid.tst.soc(end,:) == ...
                data.device.param(set_tst, loc_tst_capinitial)'.* ...
                data.device.param(set_tst, loc_tst_cap)') : ...
                'final soc of tst');
            t = 1;
            model.cons = model.cons + ( ...
                (model.var.grid.tst.soc(t,:) == ...
                (1 - data.device.param(set_tst, loc_tst_loss)').* ...
                data.device.param(set_tst, loc_tst_capinitial)'.* ...
                data.device.param(set_tst, loc_tst_cap)'+ ...
                data.device.param(set_tst, loc_tst_etachr)'.* ...
                model.var.grid.tst.h_chr(t,:) - ...
                1./data.device.param(set_tst, loc_tst_etadis)'.* ...
                model.var.grid.tst.h_dis(t,:)) : ...
                'initial soc of es');
            
            t = 2:num_period;
            model.cons = model.cons + ( ...
                (model.var.grid.tst.soc(t,:) == ...
                ones(length(t),1)*(1 - data.device.param(set_tst, loc_tst_loss)').* ...
                model.var.grid.tst.soc(t-1,:) + ...
                ones(length(t),1)*data.device.param(set_tst, loc_tst_etachr)'.* ...
                model.var.grid.tst.h_chr(t,:) - ...
                ones(length(t),1)*1./data.device.param(set_tst, loc_tst_etadis)'.* ...
                model.var.grid.tst.h_dis(t,:)) : ....
                'soc equations of es');
        end
        
        % % res  默认功率数据顺序与设备数据顺序相一致
        % % res
        if ~isempty(set_res)
            model.cons = model.cons + ( ...
                (0 <= model.var.grid.res.p <= ...
                model.var.grid.res.p_fore) : ...
                '');
        end
        % % gt
        if ~isempty(set_gt)
            model.cons = model.cons + ( ...
                (model.var.grid.gt.state.* ...
                (ones(num_period,1)*data.device.param(set_gt, loc_pmin)') <= ...
                model.var.grid.gt.p <= ...
                model.var.grid.gt.state.* ...
                (ones(num_period,1)*data.device.param(set_gt, loc_pmax)') ...
                ) : 'limit on p of gt');
            model.cons = model.cons + ( ...
                (model.var.grid.gt.h == ...
                ones(num_period,1)* ...
                data.device.param(set_gt, loc_gt_etahr)'.* ...
                (1./data.device.param(set_gt, loc_gt_eta)' - 1 - ...
                data.device.param(set_gt, loc_gt_loss)').* ...
                model.var.grid.gt.p ...
                ) : 'h-p of gt');
            model.cons = model.cons + ( ...
                (model.var.grid.gt.gas == ...
                (ones(num_period, 1)./data.device.param(set_gt, loc_gt_eta)') .* ...
                model.var.grid.gt.p ...
                ) : 'gas of gt');
        end
        % % eb
        if ~isempty(set_eb)
            model.cons = model.cons + ( ...
                (0 <= model.var.grid.eb.p <= ...
                ones(num_period,1)*data.device.param(set_eb, loc_pmax)') : ...
                'limit on p of eb');
            model.cons = model.cons + ( ...
                (model.var.grid.eb.h == ...
                (ones(num_period,1)*data.device.param(set_eb, loc_eb_eta)').* ...
                (model.var.grid.eb.p)) : ...
                'h of eb');
        end
    end

%% ---------------------------- Cost -------------------------------
    function model_cost()
        % % grid
        model.cons = model.cons + ( ...
            (model.cost.grid.pcc.buy == ...
            data.grid.price(loc_gridprice_buy,:)'.* ...
            model.var.grid.pcc.p(:,1)) : ...
            'cost of grid_buy');
        model.cons = model.cons + ( ...
            (model.cost.grid.pcc.sell == ...
            data.grid.price(loc_gridprice_sell,:)'.* ...
            model.var.grid.pcc.p(:,2)) : ...
            'cost of grid_sell');
        
        % % res
        if ~isempty(set_res)
            model.cons = model.cons + ( ...
                (model.cost.grid.res(:,1) == ...
                model.var.grid.res.p(:,:)*data.device.cost(set_res, loc_c1) + ...
                ones(num_period, length(set_res))*data.device.cost(set_res, loc_c0) + ...
                model.var.grid.res.p(:,:)*data.device.cost(set_res, loc_om) + ...
                (model.var.grid.res.p_fore(:,:) - model.var.grid.res.p(:,:)) * ...
                data.device.cost(set_res, loc_penalty)) : ...
                'cost of res');
        else
            model.cons = model.cons + ( ...
                (model.cost.grid.res(:,1) == 0) : ...
                'cost of res');
        end
        
        % % es
        if ~isempty(set_es)
            model.cons = model.cons + ( ...
                (model.cost.grid.es(:,:) == ...
                model.var.grid.es.p_chr(:,:)*data.device.cost(set_es, loc_om) + ...
                model.var.grid.es.p_dis(:,:)*data.device.cost(set_es, loc_om)) : ...
                'cost of es');
        else
            model.cons = model.cons + ( ...
                (model.cost.grid.es(:,1) == 0) : ...
                'cost of es');
        end
        
        % % tst
        if ~isempty(set_tst)
            model.cons = model.cons + ( ...
                (model.cost.grid.tst(:,:) == ...
                model.var.grid.tst.h_chr(:,:)*data.device.cost(set_tst, loc_om) + ...
                model.var.grid.tst.h_dis(:,:)*data.device.cost(set_tst, loc_om)) : ...
                'cost of tst');
        else
            model.cons = model.cons + ( ...
                (model.cost.grid.tst(:,1) == 0) : ...
                'cost of tst');
        end
        
        % % gt
        if ~isempty(set_gt)
            model.cons = model.cons + (...
                (model.cost.grid.gt(:,1) == ...
                model.var.grid.gt.gas(:,:)*data.device.cost(set_gt, loc_c1) + ...
                model.var.grid.gt.p(:,:)*data.device.cost(set_gt, loc_om)) : ...
                'cost of gt');
        else
            model.cons = model.cons + ( ...
                (model.cost.grid.gt(:,1) == 0) : ...
                'cost of gt');
        end
        
        % % eb
        if ~isempty(set_eb)
            model.cons = model.cons + ( ...
                (model.cost.grid.eb(:,1) == ...
                model.var.grid.eb.p(:,:)*data.device.cost(set_eb, loc_om)) : ...
                'cost of eb');
        else
            model.cons = model.cons + ( ...
                (model.cost.grid.eb(:,1) == 0) : ...
                'cost of eb');
        end
        % % sum
        model.cons = model.cons + ( ...
            (model.cost.grid.sum == ...
            sum(model.cost.grid.pcc.buy) - ...
            sum(model.cost.grid.pcc.sell) + ...
            sum(model.cost.grid.res) + ...
            sum(model.cost.grid.gt) + ...
            sum(model.cost.grid.eb)) : '');
    end
%% -----------------------------------------------------------------
% % SOC constraints of binary variables
    function SOC_binary()
        % % 0 <= x <= 1
        model.cons = model.cons + (( ...
            0 <= model.var.grid.es.p_chr_state <= 1) : '');
        model.cons = model.cons + (( ...
            0 <= model.var.grid.es.p_dis_state <= 1) : '');
        model.cons = model.cons + (( ...
            0 <= model.var.grid.tst.h_chr_state <= 1) : '');
        model.cons = model.cons + (( ...
            0 <= model.var.grid.tst.h_dis_state <= 1) : '');
        model.cons = model.cons + (( ...
            0 <= model.var.grid.gt.state <= 1) : '');
        
        % % x >= x^2;
        % % es
        model.cons = model.cons + (( ...
            model.var.grid.es.p_chr_state >= ...
            model.var.grid.es.p_chr_state.^2) : '');
        model.cons = model.cons + (( ...
            model.var.grid.es.p_dis_state >= ...
            model.var.grid.es.p_dis_state.^2) : '');     
        % % tst
        model.cons = model.cons + (( ...
            model.var.grid.tst.h_chr_state >= ...
            model.var.grid.tst.h_chr_state.^2) : '');
        model.cons = model.cons + (( ...
            model.var.grid.tst.h_dis_state >= ...
            model.var.grid.tst.h_dis_state.^2) : '');            
        % % gt
        model.cons = model.cons + (( ...
            model.var.grid.gt.state >= ...
            model.var.grid.gt.state.^2) : '');
    end
end











