function model_couplingrelationship_fixed(varargin)
if find(strcmp(varargin, 'DisplayTime'))
    DisplayTime = varargin{find(strcmp(varargin, 'DisplayTime'))+1};
else
    DisplayTime = 1;
end
if DisplayTime
    fprintf('%-40s\t\t','- model_fixed coupling relationship');
    t0 = clock;
end
%%
global data model_fixed;
num_heatperiod = data.period*data.interval.electricity/data.interval.heat;
num_load = size(data.buildings.param,1);
model_fixed.var.slacks.h_load_deviation_1 = sdpvar(num_heatperiod,num_load, 'full');
model_fixed.var.slacks.h_load_deviation_2 = sdpvar(num_heatperiod,num_load, 'full');
model_fixed.var.slacks.sum = sdpvar(1,1);

model_fixed.cons = model_fixed.cons + (( ...
    model_fixed.var.grid.pump.p == ...
    model_fixed.var.heatingnetwork.Power_pump(1 + ...
    data.initialParam.heatingnetwork.num_initialtime:end, :)) : '');

model_fixed.cons = model_fixed.cons + (( ...
    sum(model_fixed.var.grid.gt.h, 2) + ...
    sum(model_fixed.var.grid.eb.h, 2) + ...
    sum(model_fixed.var.grid.tst.h_dis, 2) - ...
    sum(model_fixed.var.grid.tst.h_chr, 2) == ...
    1e3*model_fixed.var.heatingnetwork.h_source(1 + ...
    data.initialParam.heatingnetwork.num_initialtime:end, :)) : '');

model_fixed.cons = model_fixed.cons + (( ...
    -model_fixed.var.slacks.h_load_deviation_1 <= ...
    1e3*model_fixed.var.heatingnetwork.h_load(1 + ...
    data.initialParam.heatingnetwork.num_initialtime:end, :) - ...
    model_fixed.var.buildings.h_load <= ...
    model_fixed.var.slacks.h_load_deviation_2): '');

model_fixed.cons = model_fixed.cons + (( ...
    model_fixed.var.slacks.h_load_deviation_1 >= 0): '');
model_fixed.cons = model_fixed.cons + (( ...
    model_fixed.var.slacks.h_load_deviation_2 >= 0): '');
model_fixed.cons = model_fixed.cons + (( ...
    1e3*model_fixed.var.slacks.sum == ...
    sum(sum(model_fixed.var.slacks.h_load_deviation_1)) + ...
    sum(sum(model_fixed.var.slacks.h_load_deviation_2))) : '');
%%
if DisplayTime
    t1 = clock;
    fprintf('%10.2f%s\n', etime(t1,t0), 's');
end
end